# Lattice
lattice_length: 6
lattice_dimension: 2

# Target
target: phi_four
parameterisation: standard
couplings:
    m_sq: 4
    g: 0

# Model
base: gaussian

model:
  - layer: nice
    n_blocks: 2
    hidden_shape: [36]
    activation: tanh
    z2_equivar: True
  - layer: global_rescaling
    scale: 1
    learnable: True

# Training length
n_batch: 2000
epochs: 2000
save_interval: 1000

# Optimizer
optimizer: Adam
optimizer_params:
    lr: 0.01

scheduler: CosineAnnealingLR
scheduler_params:
    T_max: 2000
