# Lattice
lattice_length: 6
lattice_dimension: 2

# Target
theory: phi_four
parameterisation: standard
couplings:
    m_sq: 4
    g: 0

# Model
latents: gaussian
latent_params:
    sigma: 1.0

model: real_nvp
model_params:
    n_affine: 2
    hidden_shape: [36]
    activation: leaky_relu
    z2_equivar: false

# Training
n_batch: 1000
epochs: 2000
save_interval: 3000

# Optimizer
optimizer: Adam
optimizer_params:
    lr: 0.001

scheduler: CosineAnnealingLR
scheduler_params:
    T_max: 2000
    
