# Lattice
lattice_length: 6
lattice_dimension: 2

# Target
target: phi_four
parameterisation: standard
couplings:
    m_sq: 4
    g: 0

# Model
base: gaussian
sigma: 1

model: rational_quadratic_spline
#model: real_nvp
model_params:
    n_affine: 2
    hidden_shape: [36]
    activation: tanh

    interval: 2
    gamma: 0.4

# Training length
n_batch: 1000
epochs: 1000
save_interval: 1000

# Optimizer
optimizer: Adam
optimizer_params:
    lr: 0.01

scheduler: CosineAnnealingLR
scheduler_params:
    T_max: 1000
