# Lattice
lattice_length: 6
lattice_dimension: 2

# Target
target: phi_four
parameterisation: standard
couplings:
    m_sq: 4
    g: 0

# Model
base: standard_normal
model: real_nvp
model_spec:
    n_affine: 2
    hidden_shape: [36]
    activation: leaky_relu

# Training length
n_batch: 1000
epochs: 3000
save_interval: 1000

# Optimizer
optimizer: adam
learning_rate: 0.01

scheduler: warm
T_0: 3000
