# Lattice
lattice_length: 6
lattice_dimension: 2

# Target
parameterisation: albergo2019
couplings:
    m_sq: -4
    lam: 6.975

model:
 - layer: real_nvp
   n_blocks: 6
   z2_equivar: false
   activation: leaky_relu
   final_activation: tanh
   hidden_shape: [72]
 - layer: global_rescaling
   scale: 1
   learnable: true

# Training
n_batch: 4000
epochs: 8000
save_interval: 1000

# Optimizer
optimizer: Adam
optimizer_params:
    lr: 0.005

# Scheduler
scheduler: CosineAnnealingLR
scheduler_params:
    T_max: 8000
